<Project>
  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)../../Assets/**/*" Exclude="$(MSBuildThisFileDirectory)../../Assets/**/reference/**/*;$(MSBuildThisFileDirectory)../../Assets/**/source/**/*">
      <Link>Assets/%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
